name: link-check

on:
  push:
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check links
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --verbose --no-progress './**/*.md'
